### ISSUE TITLE
Site stopped working after plugin update

### ISSUE THREAD

**Issue by lufog** [getgrav/grav-plugin-problems#31]
The site is running locally via ```php -S 0.0.0.0:80 system\router.php```

![image](https://user-images.githubusercontent.com/10379487/114610899-19baa300-9ca9-11eb-8297-616d8243f9f0.png)

Windows 10
Grav v1.7.11
Problems plugin v2.1.0

**Comment by rhukster** [comment]
Ah windows issue.. just disable `problems` plugin for now, or delete it to get your site back.

**Comment by lufog** [comment]
Ok thanks.

**Comment by mahagr** [comment]
Should be fixed for the next release.

**Comment by lufog** [comment]
I'm not sure, because I manually applied this patch to ```EssentialFolders.php``` and it not fixed the problem.

**Comment by mahagr** [comment]
@lufog Yeah, I had missing negation in there. Try again with the above commit. Thanks for testing!

**Comment by lufog** [comment]
Thanks, everything works now.
